In [3]:
import tensorflow as tf

tf.tile(tf.constant([[0, 0]]), [2, 3])

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])>

In [12]:
import tensorflow as tf

a = tf.zeros((4, 10), tf.int32)
a = tf.expand_dims(a, axis=1)
a = tf.one_hot(a, 300, axis=-1)
a = tf.repeat(a, 100, axis=1)
a.shape

TensorShape([4, 100, 10, 300])

In [15]:
import tensorflow as tf

a = tf.constant([[1, 3, 2], [4, 1, 3]], dtype=tf.int32)
a = tf.one_hot(a, 5)
a = tf.expand_dims(a, axis=1)
a = tf.repeat(a, 10, axis=1)
print(a)

tf.Tensor(
[[[[0. 1. 0. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 1. 0. 0.]]

  [[0. 1. 0. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 1. 0. 0.]]

  [[0. 1. 0. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 1. 0. 0.]]

  [[0. 1. 0. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 1. 0. 0.]]

  [[0. 1. 0. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 1. 0. 0.]]

  [[0. 1. 0. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 1. 0. 0.]]

  [[0. 1. 0. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 1. 0. 0.]]

  [[0. 1. 0. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 1. 0. 0.]]

  [[0. 1. 0. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 1. 0. 0.]]

  [[0. 1. 0. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 1. 0. 0.]]]


 [[[0. 0. 0. 0. 1.]
   [0. 1. 0. 0. 0.]
   [0. 0. 0. 1. 0.]]

  [[0. 0. 0. 0. 1.]
   [0. 1. 0. 0. 0.]
   [0. 0. 0. 1. 0.]]

  [[0. 0. 0. 0. 1.]
   [0. 1. 0. 0. 0.]
   [0. 0. 0. 1. 0.]]

  [[0. 0. 0. 0. 1.]
   [0. 1. 0. 0. 0.]
   [0. 0. 0. 1. 0.]]

  [[0. 0. 0. 0. 1.]
   [0. 1. 0. 0. 0.]
   [0. 0. 0. 1. 0.]]

  [[0. 0. 0. 0. 1.]
   [0. 1. 0. 0. 0.]
   [0. 0. 0. 1. 0

In [19]:
import tensorflow as tf

tf.sequence_mask(3, 6, dtype=tf.float32)

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 1., 1., 0., 0., 0.], dtype=float32)>

In [31]:
import tensorflow as tf
from tensorflow.python.ops.gen_array_ops import matrix_diag_part_v3

tf.linalg.diag_part(tf.constant([[1], [2], [3]]), k=[0, 0], padding_value=0)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1])>

In [44]:
hex(ord('이'))

'0xc774'