In [ ]:
import matplotlib.pyplot as plt
import librosa
import numpy as np
import soundfile as sf
import os

file_name = 'C:/Users/akswnd98/Desktop/stt/ko-audio-dataset/audio/KsponSpeech_01/KsponSpeech_0001/KsponSpeech_000001.pcm'

waveform = np.memmap(file_name, dtype='h', mode='r')
waveform = waveform / 32767

st = 1 / 16000

t = np.linspace(0, waveform.shape[0] * st, waveform.shape[0])

plt.plot(t, waveform)


In [ ]:
# with open(file_name, 'rb') as file:
#   buf = file.read()
#   pcm_data = np.frombuffer(buf, dtype='int16')
#   wav_data = librosa.util.buf_to_float(pcm_data, 2)

# sf.write('./asfd.wav', wav_data, 16000, format='WAV', endian='LITTLE', subtype='PCM_16')


In [ ]:
import matplotlib.pyplot as plt
import librosa
import librosa.display
import numpy as np
import soundfile as sf
import os

file_name = 'C:/Users/akswnd98/Desktop/stt/ko-audio-dataset/audio/KsponSpeech_01/KsponSpeech_0001/KsponSpeech_000121.pcm'

waveform = np.memmap(file_name, dtype='h', mode='r')

sr = 16000
st = 1 / sr

t = np.linspace(0, waveform.shape[0] * st, waveform.shape[0])

# plt.plot(t, waveform)
S = librosa.feature.melspectrogram(np.float32(waveform), n_fft=512, hop_length=256, window='hamming', sr=sr, n_mels=128)
log_S = librosa.power_to_db(S, ref=np.max)
# mfcc = librosa.feature.mfcc(S=log_S, n_mfcc=20)

# delta2_mfcc = librosa.feature.delta(mfcc, order=2)

# print(delta2_mfcc.shape)

plt.subplot(1, 1, 1)
librosa.display.specshow(log_S, y_axis='log', x_axis='time')
plt.colorbar()
plt.tight_layout()



In [ ]:
import tensorflow as tf

@tf.custom_gradient
def rnnt_loss (labels, logits, label_lengths, logit_lengths):
  pass
  
def get_forward_dp (labels, logits, label_lengths, logit_lengths):
  pass

def get_backward_dp (labels, logits, label_lengths, logit_lengths):
  pass




In [ ]:
import tensorflow as tf

tf.sequence_mask([1, 5, 4, 1], 10)

In [ ]:
import tensorflow as tf
import numpy as np

initializer = [np.array(0), np.array(1)]
elems = np.array([1, 0, 0, 0, 0, 0, 0])

fib = tf.scan(lambda a, x: [a[1], a[0] + a[1]], elems, initializer)

display(fib)

In [ ]:
import tensorflow as tf
import numpy as np

elems = np.array([1, 0, 0, 0, 0, 0])
initializer = (np.array(0), np.array(1))
fibonaccis = tf.scan(lambda a, _: (a[1], a[0] + a[1]), elems, initializer)
display(fibonaccis)

In [ ]:
@tf.custom_gradient
def rnnt_loss (labels, logits, label_lengths, time_lengths):
  ret = tf.zeros((logits.shape[0], time_lengths, label_lengths + 1))
  

In [ ]:
import tensorflow as tf

a = tf.convert_to_tensor([[[1, 2], [3, 4], [5, 6]], [[10, 20], [30, 40], [50, 60]]], dtype=tf.float32)
b = tf.repeat(a, 4, axis=2)
display(a.shape, b.shape)
display(b)

In [ ]:
tf.repeat(
  tf.expand_dims(
    tf.repeat(
      tf.expand_dims(
        tf.convert_to_tensor([1, 2, 3], dtype=tf.float32),
        axis=-1
      ),
      5,
      axis=-1
    ),
    axis=-1
  ),
  7,
  axis=-1
)

In [ ]:
import tensorflow as tf

i = tf.constant(0)
c = lambda i: tf.less(i, 10)
b = lambda i: [tf.add(i, 1)]
r = tf.while_loop(c, b, [i])

print(r)

In [ ]:
import tensorflow as tf

x = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32)
tf.scan(lambda a, x: a + x, x, tf.constant([0, 0, 0], dtype=tf.int32))

In [ ]:
import tensorflow as tf

x = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=tf.int32)
tf.foldl(lambda a, x: a + tf.foldl(lambda a, x: a + x, x, 0), x, 0)

In [ ]:
import tensorflow as tf

x = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=tf.int32)
tf.map_fn(lambda x: x ** 2, x)

In [ ]:
gx = tf.repeat(tf.expand_dims(tf.range(0, 5), axis=0), 5, axis=0)
gy = tf.repeat(tf.expand_dims(tf.range(0, 5), axis=-1), 5, axis=1)

tf.map_fn(lambda xy: xy[0] ** 2 + xy[1] ** 2, tf.stack([gx, gy], axis=1))


In [ ]:
tf.range(5, 10)[tf.range(0, 5)[0]]


In [ ]:
import tensorflow as tf
import numpy as np

def body (i):
  print('i: ', i)
  return [i + 1]

tf.while_loop(
  lambda i: i < 10,
  body,
  [0]
)

In [9]:
import tensorflow as tf
import numpy as np

def body (i):
  print(i)
  return [i + 1]

tf.while_loop(
  lambda i: i < 10,
  body,
  [0]
)

0
1
2
3
4
5
6
7
8
9


[<tf.Tensor: shape=(), dtype=int32, numpy=10>]

In [ ]:
import tensorflow as tf

model = tf.keras.Sequential()
fc = tf.keras.layers.Dense(100, use_bias=False)

model.add(fc)

model(tf.keras.Input(shape=(None, 6)))
model.summary()

In [ ]:
import tensorflow as tf

enc_outputs = tf.zeros((16, 1548, 512))
dec_outputs = tf.zeros((16, 146, 512))

(tf.expand_dims(enc_outputs, axis=2) + tf.expand_dims(dec_outputs, axis=1)).shape

In [ ]:
import tensorflow as tf

enc_outputs = tf.keras.Input((None, 512), 100)
dec_outputs = tf.keras.Input((None, 512), 100)

print(tf.repeat(tf.expand_dims(enc_outputs, axis=2), dec_outputs.shape[1], axis=2))

joint_inputs = tf.concat([
  tf.repeat(tf.expand_dims(enc_outputs, axis=2), dec_outputs.shape[1], axis=2),
  tf.repeat(tf.expand_dims(dec_outputs, axis=1), enc_outputs.shape[1], axis=1)
], axis=-1)



In [6]:
import tensorflow as tf

a = tf.constant([[[1, 2, 3, 4], [5, 6, 7, 8]], [[10, 20, 30, 40], [50, 60, 70, 80]]])
tf.reduce_sum(a, axis=2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 10,  26],
       [100, 260]])>

In [8]:
import tensorflow as tf

T = tf.constant([[1, 2, 3], [4, 5, 6]])
T = tf.expand_dims(T, axis=1)
T = tf.tile(T, [1, 5, 1])
T = tf.one_hot(T, 30)
print(T.shape)

(2, 5, 3, 30)


In [18]:
import tensorflow as tf

T = tf.constant([[[1, 2, 3], [4, 5, 6]]])
T = tf.transpose(T, perm=[1, 0, 2])
T.shape

TensorShape([2, 1, 3])

In [26]:
import tensorflow as tf

a = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
b = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)

tf.math.reduce_logsumexp(tf.stack([a, b], axis=0), axis=0)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.6931472, 2.6931472, 3.6931472],
       [4.693147 , 5.693147 , 6.693147 ]], dtype=float32)>

In [16]:
import tensorflow as tf

x = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
y = tf.constant([[2, 2, 2], [3, 3, 3]], dtype=tf.float32)
z = tf.constant(321, dtype=tf.float32)

@tf.custom_gradient
def custom_sin_plus_exp (x, y, z):
  def grad (upstream):
    return upstream * tf.cos(x), upstream * tf.exp(y), None
  return tf.sin(x) + tf.exp(y), grad

with tf.GradientTape() as tape:
  tape.watch(x)
  tape.watch(y)
  tape.watch(z)
  w = custom_sin_plus_exp(x, y, z)

grad = tape.gradient(w, (x, y, z))
print(w)
print(grad)

print('--------------------')

x = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
y = tf.constant([[2, 2, 2], [3, 3, 3]], dtype=tf.float32)

with tf.GradientTape() as tape:
  tape.watch(x)
  tape.watch(y)
  z = tf.sin(x) + tf.exp(y)

grad = tape.gradient(z, (x, y))
print(z)
print(grad)


tf.Tensor(
[[ 8.230527  8.298353  7.530176]
 [19.328735 19.126614 19.806122]], shape=(2, 3), dtype=float32)
(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.5403023 , -0.4161468 , -0.9899925 ],
       [-0.65364367,  0.28366217,  0.96017027]], dtype=float32)>, <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 7.389056,  7.389056,  7.389056],
       [20.085537, 20.085537, 20.085537]], dtype=float32)>, None)
--------------------
tf.Tensor(
[[ 8.230527  8.298353  7.530176]
 [19.328735 19.126614 19.806122]], shape=(2, 3), dtype=float32)
(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.5403023 , -0.4161468 , -0.9899925 ],
       [-0.65364367,  0.28366217,  0.96017027]], dtype=float32)>, <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 7.389056,  7.389056,  7.389056],
       [20.085537, 20.085537, 20.085537]], dtype=float32)>)


In [9]:
def rnnt_loss (logits, labels, time_lengths, label_lengths):
  pr = pr_loss(tf.nn.softmax(logits, axis=-1), labels, time_lengths, label_lengths)
  ret = tf.reduce_sum(pr)
  return ret

@tf.custom_gradient
def pr_loss (pr, labels, time_lengths, label_lengths):
  pr = pr
  batch_size = pr.shape[0]
  max_time_lengths = pr.shape[1]
  max_label_lengths = pr.shape[2]

  def get_alpha (pr, labels, time_lengths, label_lengths):
    alpha = np.zeros((batch_size, max_time_lengths, max_label_lengths), dtype=np.float32)
    for b in range(batch_size):
      alpha[b][0][0] = 1

      for t in tf.range(time_lengths[b]):
        for u in tf.range(label_lengths[b]):
          if t + 1 >= time_lengths[b] or u + 1 >= label_lengths[b]:
            continue
          alpha[b][t + 1][u] += alpha[b][t][u] * pr[b][t][u][0]
          alpha[b][t][u + 1] += alpha[b][t][u] * pr[b][t][u][labels[b][u + 1]]

    return alpha
  
  def get_beta (pr, labels, time_lengths, label_lengths):
    beta = np.zeros((batch_size, max_time_lengths, max_label_lengths), dtype=np.float32)
    for b in range(batch_size):
      beta[b][-1][-1] = pr[b][-1][-1][0]
      for t in reversed(range(time_lengths[b])):
        for u in reversed(range(label_lengths[b])):
          if t - 1 < 0 or u - 1 < 0:
            continue
          beta[b][t - 1][u] += beta[b][t][u] * pr[b][t][u][0]
          beta[b][t][u - 1] += beta[b][t][u] * pr[b][t][u][labels[b][u - 1]]
    
    return beta

  alpha = get_alpha(pr, labels, time_lengths, label_lengths)
  beta = get_beta(pr, labels, time_lengths, label_lengths)
  
  total_pr = alpha[:, 0, 0] * beta[:, 0, 0]
  print('total_pr', total_pr.shape)

  vocab_size = pr.shape[-1]
  def grad (upstream):
    ret = np.zeros((batch_size, max_time_lengths, max_label_lengths, vocab_size), dtype=np.float32)
    for b in range(batch_size):
      for t in range(time_lengths[b]):
        for u in range(label_lengths[b]):
          if u + 1 < label_lengths[b]:
            ret[b][t][u][labels[b][u + 1]] = upstream[b] * -alpha[b][t][u] / (total_pr[b] + 1e-9) * beta[b][t][u + 1]
          if t + 1 < time_lengths[b]:
            ret[b][t][u][0] = upstream[b] * -alpha[b][t][u] / (total_pr[b] + 1e-9) * beta[b][t + 1][u]
    print('grad ret: ', tf.reduce_sum(tf.reduce_sum(ret)))
    return [ret] + [None] * 3

  return -tf.math.log(total_pr + 1e-9), grad


-0.6536436208636119

In [1]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 1939608577771910648
 xla_global_id: -1,
 name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 5742252032
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 13666638374042260754
 physical_device_desc: "device: 0, name: NVIDIA GeForce RTX 3060 Ti, pci bus id: 0000:01:00.0, compute capability: 8.6"
 xla_global_id: 416903419]

In [10]:
import tensorflow as tf

tf.reverse(tf.constant([1, 2, 3, 4]), axis=[-1])

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 3, 2, 1])>

In [6]:
import tensorflow as tf

tf.reduce_logsumexp(tf.constant([-10000, -9009], dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=-9009.0>

In [8]:
a = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)

tf.pad(a, [[1, 1], [1, 0]])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 4., 5., 6.],
       [0., 0., 0., 0.]], dtype=float32)>

In [10]:
import tensorflow as tf
import numpy as np

tf.reduce_logsumexp(np.array([1, 2, 3, 4], dtype=np.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=4.44019>

In [15]:
tf.reduce_logsumexp(tf.stack([tf.constant(1, dtype=tf.float32), tf.constant(2, dtype=tf.float32)]))

<tf.Tensor: shape=(), dtype=float32, numpy=2.3132617>

In [55]:
import tensorflow as tf
from tensorflow.python.ops.gen_array_ops import matrix_diag_part_v3

LOG_0 = float('-inf')

truth_log_pr = tf.math.log_softmax(tf.random.uniform((10, 4, 2), dtype=tf.float32), axis=-1)

time_size = tf.shape(truth_log_pr)[-2]
label_size = tf.shape(truth_log_pr)[-1]

padded_truth_log_pr = tf.reverse(truth_log_pr, axis=[-2])
padded_truth_log_pr = tf.pad(
  padded_truth_log_pr,
  [[0, 0], [0, 0], [tf.shape(padded_truth_log_pr)[-2] - 1, 0]],
  constant_values=LOG_0
)
truth_diag = tf.linalg.diag_part(
  padded_truth_log_pr,
  k=(0, tf.shape(padded_truth_log_pr)[-1] - 1),
  padding_value=LOG_0,
  align='LEFT_RIGHT'
)
truth_diag = tf.pad(truth_diag, [[0, 0], [0, 0], [0, 1]], constant_values=LOG_0)

blank_log_pr = tf.math.log_softmax(tf.random.uniform((10, 4, 2), dtype=tf.float32), axis=-1)

reversed_blank_log_pr = tf.reverse(blank_log_pr, axis=[-2])
padded_blank_log_pr = tf.pad(
  reversed_blank_log_pr,
  [[0, 0], [0, 0], [tf.shape(reversed_blank_log_pr)[-2] - 1, 0]],
  constant_values=LOG_0
)
blank_diag = tf.linalg.diag_part(
  padded_blank_log_pr,
  k=(0, tf.shape(padded_blank_log_pr)[-1] - 1),
  padding_value=LOG_0,
  align='LEFT_RIGHT'
)
blank_diag = tf.pad(blank_diag, [[0, 0], [0, 0], [1, 0]], constant_values=LOG_0)

initial_diag = tf.concat([
  -0.5 * tf.ones((tf.shape(blank_diag)[0], 1), dtype=tf.float32),
  LOG_0 * tf.ones((tf.shape(blank_diag)[0], tf.shape(blank_diag)[-1] - 2), tf.float32),
], axis=-1)

def step (a, x):
  t, b = x
  return (
    tf.reduce_logsumexp(
      tf.stack([
        tf.concat([a, LOG_0 * tf.ones((tf.shape(a)[0], 1), dtype=tf.float32)], axis=-1) + t,
        tf.concat([LOG_0 * tf.ones((tf.shape(a)[0], 1), dtype=tf.float32), a], axis=-1) + b
      ]), axis=0
    )[:, : -1]
  )

beta_diag = tf.concat([
  tf.expand_dims(initial_diag, axis=0),
  tf.scan(step,
    (tf.transpose(truth_diag, perm=[1, 0, 2]),
    tf.transpose(blank_diag, perm=[1, 0, 2])),
    initial_diag
  )
], axis=0)

beta_diag = tf.transpose(beta_diag, [1, 0, 2])

beta = tf.linalg.diag_part(beta_diag, k=(-label_size + 1, 0))
beta = tf.transpose(beta, [0, 2, 1])
beta = tf.reverse(beta, axis=[1, 2])

print('truth_log_pr: ', truth_log_pr[0])
print()

print('blank_log_pr: ', blank_log_pr[0])
print()

print('beta: ', beta[0])
print()


truth_log_pr:  tf.Tensor(
[[[-1.130055   -0.39010686]
  [-0.51448405 -0.91082823]
  [-0.7144644  -0.67227495]
  [-0.6908281  -0.69547164]]

 [[-0.85471773 -0.5540868 ]
  [-0.50312513 -0.9279538 ]
  [-1.1336892  -0.38837752]
  [-0.6542736  -0.7335932 ]]

 [[-1.0393354  -0.4364755 ]
  [-0.6929791  -0.69331527]
  [-0.97669554 -0.4724921 ]
  [-0.3889923  -1.132395  ]]

 [[-0.58488816 -0.8145651 ]
  [-0.6651009  -0.7220029 ]
  [-0.64109856 -0.7480543 ]
  [-0.43011904 -1.0510563 ]]

 [[-0.88227856 -0.5341606 ]
  [-0.43891025 -1.0349016 ]
  [-0.930638   -0.5013738 ]
  [-1.0323143  -0.44033873]]

 [[-0.5445258  -0.8677787 ]
  [-0.7529481  -0.63672155]
  [-0.6403059  -0.74893713]
  [-0.790834   -0.60415965]]

 [[-0.78091043 -0.6124688 ]
  [-0.45736647 -1.0022527 ]
  [-0.7442542  -0.6445256 ]
  [-1.0011619  -0.45799956]]

 [[-0.436761   -1.038814  ]
  [-0.7976619  -0.59852946]
  [-0.87718576 -0.5377719 ]
  [-0.3719611  -1.1691885 ]]

 [[-0.61135334 -0.7822321 ]
  [-0.7641891  -0.62681925]
  [-0.

In [44]:
import tensorflow as tf
from tensorflow.python.ops.gen_array_ops import matrix_diag_part_v3

LOG_0 = float('-inf')

truth_log_pr = tf.math.log_softmax(tf.random.uniform((10, 4, 2), dtype=tf.float32), axis=-1)

time_size = tf.shape(truth_log_pr)[-2]
label_size = tf.shape(truth_log_pr)[-1]

print('truth_log_pr: ', truth_log_pr)
print()

reversed_truth_log_pr = tf.reverse(truth_log_pr, axis=[-2])
padded_truth_log_pr = tf.pad(
  reversed_truth_log_pr,
  [[0, 0], [0, 0], [tf.shape(reversed_truth_log_pr)[-2] - 1, 0]],
  constant_values=LOG_0
)

print('padded_truth_log_pr: ', padded_truth_log_pr)
print()

truth_diag = tf.linalg.diag_part(
  padded_truth_log_pr,
  k=(0, tf.shape(padded_truth_log_pr)[-1] - 1),
  padding_value=LOG_0,
  align='LEFT_RIGHT'
)
truth_diag = tf.reverse(truth_diag, axis=[-2])

print('truth_diag: ', truth_diag)
print()

truth_diag = tf.pad(truth_diag, [[0, 0], [0, 0], [1, 0]], constant_values=LOG_0)

print('truth_diag: ', truth_diag)
print()

blank_log_pr = tf.math.log_softmax(tf.random.uniform((10, 4, 2), dtype=tf.float32), axis=-1)

print('blank_log_pr: ', blank_log_pr)
print()

reversed_blank_log_pr = tf.reverse(blank_log_pr, axis=[-2])
padded_blank_log_pr = tf.pad(
  reversed_blank_log_pr,
  [[0, 0], [0, 0], [tf.shape(reversed_blank_log_pr)[-2] - 1, 0]],
  constant_values=LOG_0
)

print('padded_blank_log_pr: ', padded_blank_log_pr)
print()

blank_diag = tf.linalg.diag_part(
  padded_blank_log_pr,
  k=(0, tf.shape(padded_blank_log_pr)[-1] - 1),
  padding_value=LOG_0,
  align='LEFT_RIGHT'
)
blank_diag = tf.reverse(blank_diag, axis=[-2])

print('blank_diag: ', blank_diag)
print()

blank_diag = tf.pad(blank_diag, [[0, 0], [0, 0], [0, 1]], constant_values=LOG_0)

print('blank_diag: ', blank_diag)
print()

print('truth, blank diags: ')
print(truth_diag)
print(blank_diag)
print()

initial_diag = tf.concat([
  LOG_0 * tf.ones((tf.shape(blank_diag)[0], tf.shape(blank_diag)[-1] - 2), tf.float32),
  tf.zeros((tf.shape(blank_diag)[0], 1), dtype=tf.float32)
], axis=-1)

print('initial_diag: ', initial_diag)

def step (a, x):
  t, b = x
  return (
    tf.reduce_logsumexp(
      tf.stack([
        tf.concat([LOG_0 * tf.ones((tf.shape(a)[0], 1), dtype=tf.float32), a], axis=-1) + t,
        tf.concat([a, LOG_0 * tf.ones((tf.shape(a)[0], 1), dtype=tf.float32)], axis=-1) + b
      ]), axis=0
    )[:, 1: ]
  )

alpha_diag = tf.concat([
  tf.expand_dims(initial_diag, axis=0),
  tf.scan(step, (tf.transpose(truth_diag, perm=[1, 0, 2]), tf.transpose(blank_diag, perm=[1, 0, 2])), initial_diag)
], axis=0)

alpha_diag = tf.transpose(alpha_diag, perm=[1, 0, 2])

print('alpha_diag: ', alpha_diag.shape)
print()

alpha_diag = tf.reverse(alpha_diag, axis=[-1])
alpha_diag = tf.transpose(alpha_diag, perm=[0, 2, 1])
alpha = tf.linalg.diag_part(alpha_diag, k=(0, label_size - 1))
alpha = tf.reverse(alpha, axis=[-2])
alpha = tf.transpose(alpha, perm=[0, 2, 1])

print('truth_log_pr: ', truth_log_pr[0])
print()

print('blank_log_pr: ', blank_log_pr[0])
print()

print('alpha: ', alpha[0])
print()


truth_log_pr:  tf.Tensor(
[[[-0.67612386 -0.7104653 ]
  [-0.5634695  -0.8421825 ]
  [-0.86673194 -0.5452842 ]
  [-0.6707279  -0.7160807 ]]

 [[-0.571957   -0.8310764 ]
  [-1.1671551  -0.37287855]
  [-0.61006975 -0.7837571 ]
  [-0.72120595 -0.66585433]]

 [[-1.2115937  -0.35342655]
  [-0.5360782  -0.8795686 ]
  [-0.8222583  -0.57881576]
  [-0.9667809  -0.4785283 ]]

 [[-0.50036937 -0.9321831 ]
  [-0.4585955  -1.0001369 ]
  [-0.8140696  -0.5852821 ]
  [-0.94123316 -0.4945364 ]]

 [[-0.8894882  -0.5291015 ]
  [-0.5176766  -0.90610147]
  [-0.8575294  -0.5520103 ]
  [-0.66230536 -0.7249706 ]]

 [[-0.9113492  -0.5141337 ]
  [-0.5985849  -0.7975944 ]
  [-0.90736467 -0.51682097]
  [-1.2253842  -0.34763712]]

 [[-0.8703257  -0.54268646]
  [-0.5609181  -0.84556425]
  [-0.5725831  -0.83026564]
  [-0.7120691  -0.6745768 ]]

 [[-0.61248493 -0.7808913 ]
  [-0.8783347  -0.53695446]
  [-0.3835294  -1.1439823 ]
  [-0.7462211  -0.64274865]]

 [[-0.72458047 -0.662672  ]
  [-0.5694376  -0.83435035]
  [-0.

In [2]:
import tensorflow as tf

tf.reduce_logsumexp(tf.constant([-46.68079 + -7.0359154, -47.31695 + -6.9177256], dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=-53.249374>